name: Breed_dog
description: Breed dog classification

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  image: ^4.0.17
  path: ^1.8.3
  path_provider: ^2.0.15
  image_picker: ^0.8.8
  tflite_flutter: ^0.10.4
  firebase_core: ^2.14.0
  flutter_launcher_icons: ^0.12.0 # Specify the desired version
  firebase_database: ^10.4.0
  cached_network_image: ^3.3.1
  supabase_flutter: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4

flutter:
  assets:
    - assets/images/
    - assets/models/
    - lib/assets/images/

flutter_launcher_icons:
  image_path: "assets/images/old_icon.png"  # Replace with the path to your old icon
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
